add mcqs-2027-s1 & other files
Epidocs/Past-Exams pull request #103
Opened 2023-07-15 13:45 UTC by Clarisse78

(student) : with answers of student (not correction)
all : subject / correction / AS (if there is)

2026-s1 :
- final-maths : subject
- midterm-maths : subject fr/en
- midterm-phys : subject fr/en + rename correction

2027-s1 : 
- final-cie : Subject (student) & Correction
- final-te : all (subjects & docs)
- MCQs : all (with correction in red)
- midterm-cie : Subject (Student)
- Seminar-MCQs : all (with correction in red)

2027-s2 : 
- final-cie : Subject (student)
- final-te : Subject (docs)
- final-tim : Subject

All files have been compressed
MCQs-s1 and subject SH has a lot of pages so I can’t do more without a great loss of quality

2023-07-28 23:10 UTC, matiboux requested changes
Hi,
First of all, thank you for your contribution.
Sorry for the delay, got busy.

Thank you for the new files.

I made a few comments on modified files.
I hope you can review them, and let me know what you think!

2023-07-28 23:10 UTC, matiboux commented on S1/Finals/TE/2027/final-2027-s1-te-subject.pdf
This file, `final-2027-s1-te-subject.pdf`, was added.
Comparing it to `final-2027-s1-te-answer_sheet.pdf`, that was deleted:
- It is heavier,
- It has the same content (correct me if I'm wrong),
- It has less details (colorless),
- Its name is wrong as it contains answers and not only the subject.

In my opinion, the previous file should be kept instead of this new file.
_(also renamed, see comment on `final-2027-s1-te-answer_sheet.pdf`.)_

2023-07-28 23:10 UTC, matiboux commented on S1/Finals/TE/2027/final-2027-s1-te-answer_sheet.pdf
_See comment on `final-2027-s1-te-subject.pdf`._

This file should be restored, and renamed `final-2027-s1-te-correction.pdf`.

2023-07-28 23:10 UTC, matiboux commented on S1/MCQs/2027/mcq-2027-s1-04-correction.csv
This file, `mcq-2027-s1-04-correction.csv`, was deleted.

Why was it deleted?
Were the answers wrong?

2023-07-28 23:10 UTC, matiboux commented on S1/MCQs/2027/mcq-2027-s1-04.pdf
This file, `mcq-2027-s1-04.pdf`, was modified.
Compared to the previous revision:
- It is lighter, which is a good point,
- However, its name should indicate that it contains answers and not only the subject,
- As such, the previous revision that did not contain answer was more relevant.

We could:
- Keep the previous revision as `mcq-2027-s1-04.pdf`,
- Keep this new file as `mcq-2027-s1-04-correction.pdf`.

What do you think?

2023-07-30 15:10 UTC, Clarisse78 commented on S1/Finals/TE/2027/final-2027-s1-te-subject.pdf
- The previous one did not contain the documents but only the answer sheet. It is heavier because it contains all the documents.
- Color is not necessary because everything is blue and black (no "real" correction)
- It's not the correction but my writing because I didn't have it without

2023-07-30 15:15 UTC, Clarisse78 commented on S1/MCQs/2027/mcq-2027-s1-04.pdf
All qcms 2027-s1 are with corrections in red.
I did not find it necessary to keep the correction file for the qcm 4 knowing that it was directly on the qcm sheet.

2023-07-30 16:51 UTC, matiboux commented on S1/Finals/TE/2027/final-2027-s1-te-subject.pdf
Hot!🔥
I understand now it has more content with the documents.
I will scroll more than two pages next time. 👀

Also, it not being the correction makes more sense for the original file name.
Thank you for the clarification!

2023-07-30 16:52 UTC, matiboux commented on S1/Finals/TE/2027/final-2027-s1-te-answer_sheet.pdf
> It's not the correction but my writing because I didn't have it without

2023-07-30 16:58 UTC, matiboux commented on S1/MCQs/2027/mcq-2027-s1-04.pdf
This makes sense.
I personally would have kept both files but it does seem unnecessary.
I guess the corrections being in red should be obvious enough.

2023-07-30 16:58 UTC, matiboux commented on S1/MCQs/2027/mcq-2027-s1-04-correction.csv
> I did not find it necessary to keep the correction file for the qcm 4 knowing that it was directly on the qcm sheet.

2023-07-30 17:02 UTC, matiboux approved these changes
Alright, all good!
Thank you for the clarification and for the many files. ❤️

2023-07-30 17:02 UTC, merged