add finals s3 + english archi midterms
Epidocs/Past-Exams pull request #125
Opened 2023-12-27 15:26 UTC by 1somniak

* **Contributing guidelines check**
- [x] Check that this pull request follows our contributing guidelines

* **Are you adding new files?**
- [ ] Did you run the `pdfshrink.py` script on your files?

* **Comment your changes:**
I add S3 finals 2027 files, and some modifications from midterms of S3 2027
I used ILovePDF to compress files

2023-12-28 14:32 UTC, matiboux requested changes
Thank you for your contribution!

I note that you used ILovePDF to compress files, which is fine.
However, did you forget to compress files in `S3/Finals/Archi/2026/`? The four files you added in this folder are 2.55MB large.

2023-12-31 14:12 UTC, 1somniak commented
I have compressed the files
This is I hope my last contribution of the prepa :)
Happy new year !

2023-12-31 14:15 UTC, matiboux approved these changes

2023-12-31 14:17 UTC, matiboux commented
> I have compressed the files

Thanks a lot!

> This is I hope my last contribution of the prepa :)
> Happy new year !

Happy new year to you too! Wishing you well 😄

2023-12-31 14:18 UTC, merged