added multiple things
Epidocs/Past-Exams pull request #142
Opened 2024-10-24 18:58 UTC by bymedeu

Since last time i have:
- renamed every "Maths" folder in "Maths PC" since a new maths subject was added last year, and will soon be on past exams
- added almost every subject of the s3 2028 midterm, exept "Ethique", English, "THLR"
- added the correction of both math subjects
I might have forgotten to pull and force merge some things, so not sure if [your last commit](https://github.com/Epidocs/Past-Exams/commit/0d0c09f7ad0477448e13e4e630d8551a846536b3)  is still on my brach

2024-10-24 18:59 UTC, bymedeu commented
Seems like the compress PDF files commit worked :)

2024-12-02 02:04 UTC, matiboux requested changes
Wow this was a pain to review (and I procrastinated a lot, I admit — _damn, a month already?_).

Next time, please update (merge) your branch with upstream (`Epidocs:master`) for more readable changelogs. Currently, the files changelog shows new changes as well as changes from your last merged PR because it was not updated since. TLDR: Too much changes shown.

However, that's not the issue preventing me from merging right now, which is:

Upon review, I've noticed the large added file `S3/Midterms/Algo/2028/midterm-2028-s3-algo-subject.pdf`. **Please compress this file!** You can use the provided script in the repo, or external online compression tools.

Still, thank you for your contribution!

2025-10-21 15:28 UTC, Nixuge commented
Any news? This pr's been stalling for almost a year now

2025-10-21 19:23 UTC, matiboux commented
> Any news? This pr's been stalling for almost a year now

@Nixuge No news on my end.
The TLDR review "_Too much diff with upstream branch._" still applies to this PR.
And in its state now it got nearly impossible to merge with upstream.
Also, as a maintainer, the author did not grant me write access to their fork, and so I am unable to edit the PR changes.

You are welcome to replicate changes in smaller and cleaner PRs if you'd like.

2026-06-28 15:36 UTC, closed without merging

2026-06-28 15:47 UTC, Nixuge commented
Hello again, are the 2028 S3 files still available somewhere now that the PR repo has been nuked?

2026-07-05 15:23 UTC, bymedeu commented
On the "files changed" tab of this PR

2026-07-05 15:25 UTC, Nixuge commented
> On the "files changed" tab of this PR

The files aren't accessible (404) when the head repo is deleted/private

2026-07-06 08:35 UTC, matiboux commented
> The files aren't accessible (404) when the head repo is deleted/private

The way things work on GitHub: a deleted fork does not delete its content because the git backend is shared across forks. You can access files by replacing the username in the 404 page by `Epidocs`.

You may also browse the repository at the latest commit of this PR in the commits tabs or here: https://github.com/Epidocs/Past-Exams/tree/a93145739c5b8ead0e97bcbdea694e3398fd3746.

_Notice the warning: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."_

If someone wants to copy the files over some new PR, feel free to.

EDIT: I did copy the files over to PR #174, which has been merged.